modLoader="javafml"
loaderVersion="[47,)"
license="GPLv3"
issueTrackerURL="https://github.com/Camawama/FullStop/issues"

[[mods]]
modId="fullstop"
version='1.20.1-1.3.0-beta'
displayName="Full Stop!"
displayURL="https://github.com/Camawama/FullStop"
logoFile="fullstop.png"
credits="Special thanks go to kawaiicakes for creating the original mod, Velocity Based Damage Deluxe, as well as to all the talented artists who contribute."
authors="cama, joe_devel"
description='''
Speed thrills, but it hurts. Expect the unexpected!
'''

[[dependencies.fullstop]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.fullstop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.1]"
    ordering="NONE"
    side="BOTH"
